config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role:[:user,:company,:admin]
  after_initialize :set_default_role, :if => :new_record?

def set_default_role
  self.role ||= :user
end


         has_many :clients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  
  #set so anyone can look at the clients without logging in-------------------------------------
  #before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_user!, except: [:index]

  #must be correct_user to make changes to clients
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    #@client = Client.new
    @client = current_user.clients.build
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    #@client = Client.new(client_params)
    @client = current_user.clients.build(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @client = current_user.clients.find_by(id: params[:id])
    # correct user is that which has been associated with this ID
    #otherwise error message
    redirect_to clients_path, notice: "Not Authorized to Access This Client" if @client.nil?
    #if the friend id != current_user id it will be nil and youll get this message

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :phone, :email, :mail_address, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    #@about_me = "My name is Buck Ashburn"

  end
  
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clients/_client.html.erb
<tr>
  <td><%= link_to client.first_name + " " + client.last_name, client, class:"link-secondary" %></td>
  <td><%= client.email %></td>
  <td><%= client.phone %></td>
  <td><%= client.mail_address %></td>  
  <td><%= client.user_id %></td>  
</tr>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

      <div class="col-3">
          <div class="row, pt-1">
            <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
          </div>

          <div class="row, pt-1">
            <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
          </div>

          <div class="row, pt-1">
            <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
          </div>

          <div class="row, pt-1">
            <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
          </div>

          <div class="row, pt-1">
            <%= form.text_field :mail_address, class:"form-control", placeholder:"Address" %>
          </div>

          <div class="row, pt-1">
            <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
          </div>

          <div class="row, pt-4">
            <%= form.submit class:"btn btn-success" %>
          </div>
      </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div class="row pt-0">
  <div class="col-1">
    <%= link_to "Show this client", @client, class:"btn btn-outline-secondary" %>
  </div>
  <div class="col-1">
    <%= link_to "Back to clients", clients_path, class:"btn btn-outline-dark"%>
  </div>
</div>

app/views/clients/index.html.erb
<h1>Clients</h1>

<div id="clients">
     <table class="table table-striped table-hover w-auto">
       <thead scope;="row" style="background-color: #11d47c;">
         <tr>
           <th scope="col" class="text-white">Name</th>
           <th scope="col" class="text-white">Email</th>
           <th scope="col" class="text-white">Phone</th>
           <th scope="col" class="text-white">Address</th>
           
         </tr>
       </thead>
      <tbody>

        <% @clients.each do |client| %>
          <% if client.user == current_user %>
            <tr>
              <td><%= link_to client.first_name + " " + client.last_name, client, class:"link-secondary" %></td>
              <td><%= client.email %></td>
              <td><%= client.phone %></td>
              <td><%= client.mail_address %></td>   
            </tr>
            <% end %>
          <% end %>
      </tbody>
    </table>
  
</div>

<%= link_to "New client", new_client_path, class:"btn btn-success" %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<%= link_to "Client List", clients_path, class:"btn btn-outline-dark" %>

app/views/clients/show.html.erb
<div class="card w-50">
  <h5 class="card-header"><%= @client.first_name + " " + @client.last_name %></h5>
  <div class="card-body">
    <h5 class="card-title"><%= @client.phone %></h5>
    <div class="mt-3">
      <p class="card-text"><%= @client.email %></p>
      <p class="card-text"><%= @client.mail_address %></p>
    </div>
    
    <div class="row mt-3">
      <div class="col-9">
        <%= link_to "Edit this client", edit_client_path(@client), class:"btn btn-outline-primary" %>
        <%= link_to "Client list", clients_path, class:"btn btn-outline-dark" %>
      </div>
      <div class="col align-self-end">
        <%= button_to "Delete this client", @client, method: :delete, class:"btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-xxl" style="background-color: #10c272;">
  <div class="container-fluid">

    <a class="navbar-brand">
      <img src="/images/leaf.jpg" width="40" height="40" class="me-2" style="border-radius: 50%;">
    </a> 
    
    <button class="navbar-toggler justify-content-end" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-1 mb-lg-0">
        
        
        <li class="nav-item, mt-1">
          <%= link_to "Samara", root_path, class:"nav-link, h2 me-3" %>
        </li>

        <li class="nav-item, fs-4">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
            <li class="nav-item, fs-4">
              <%= link_to "Clients", clients_path, class:"nav-link" %>
            </li>

            <li class="nav-item, fs-4">
              <%= link_to "Add Client", new_client_path, class:"nav-link" %>
            </li>
            <li class="nav-item, fs-4">
                <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
            </li>
        <% else %>
            <li class="nav-item, fs-4">
              <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item, fs-4">
              <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
            </li>
        <% end %>

        <% if user_signed_in? %>
            <div class="ms-2 mt-1">
              <li class="nav-item, fs-5 mt-1">
                <%= link_to "Sign Out", destroy_user_session_path, class:"btn btn-outline-light" %>
              </li>
            </div>
            
            <li class="ms-2 mt-3">
              <%= current_user.role + " "%> 
            </li>
            <li class="ms-2 mt-3">
              <%= current_user.email %>
            </li>
          
        <% end %>
        

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Find Name or Address" aria-label="Search">
        <button class="btn btn-dark" type="submit">Search</button>
      </form>
    </div>

  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>
We manage tree company's data

app/views/home/index.html.erb
<h1>Samara</h1>
<p>Tree Company Management Utility</p>

app/views/layouts/_alerts.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
<div class="alert alert-success d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
  <div>
    <%= notice %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samara</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "home/header" %>
    <br/>
    <div class="container-flex, ps-3">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</html>